#!/usr/bin/env bash
# Parse the committed network.local.toml into env consumable by
# docker-compose (harness/.env) and the demo (ts/apps/demo/.env.local).
# Single source of truth: the TOML. Everything here is regenerated on every
# boot; neither output file is committed.
#
# The keeper needs no rendering: harness/keeper.toml is static (service
# names + public anvil keys) and reads the contract addresses itself from
# the network file mounted next to it.

set -euo pipefail

HARNESS="$(cd "$(dirname "$0")" && pwd)"
TOML="$HARNESS/network.local.toml"

# toml_get <section> <key>
toml_get() {
  awk -v section="[$1]" -v key="$2" '
    /^\[/ { current = $0 }
    current == section && $1 == key && $2 == "=" {
      gsub(/"/, "", $3); print $3; exit
    }
  ' "$TOML"
}

CHAIN_ID="$(toml_get network chain_id)"
IDENTITY_NAMES="$(toml_get identity identity_names)"
GITHUB_IDENTITY_VERIFIER="$(toml_get identity github_identity_verifier)"
X_IDENTITY_VERIFIER="$(toml_get identity x_identity_verifier)"
GOOGLE_IDENTITY_VERIFIER="$(toml_get identity google_identity_verifier)"
X_CLIENT_ID="$(toml_get platforms x_client_id)"
GOOGLE_CLIENT_ID="$(toml_get platforms google_client_id)"

for v in CHAIN_ID IDENTITY_NAMES GITHUB_IDENTITY_VERIFIER X_IDENTITY_VERIFIER GOOGLE_IDENTITY_VERIFIER; do
  [ -n "${!v}" ] || { echo "ERROR: could not read $v from $TOML"; exit 1; }
done

# ── compose interpolation env ──────────────────────────────────────────────
cat > "$HARNESS/.env" <<EOF
# GENERATED by render-env.sh from network.local.toml — do not edit, do not commit.
GITHUB_IDENTITY_VERIFIER=$GITHUB_IDENTITY_VERIFIER
X_IDENTITY_VERIFIER=$X_IDENTITY_VERIFIER
EOF

# ── demo env ───────────────────────────────────────────────────────────────
DEMO_ENV="$HARNESS/../ts/apps/demo/.env.local"
cat > "$DEMO_ENV" <<EOF
# GENERATED by harness/render-env.sh from harness/network.local.toml.
VITE_IDENTITY_NAMES_ADDRESS=$IDENTITY_NAMES
VITE_RPC_URL=http://127.0.0.1:8545
VITE_API_URL=http://localhost:8722
VITE_CHAIN_ID=$CHAIN_ID
VITE_NOTARY_WS_URL=http://127.0.0.1:7048
VITE_X_CLIENT_ID=$X_CLIENT_ID
VITE_GMAIL_CLIENT_ID=$GOOGLE_CLIENT_ID
VITE_GOOGLE_IDENTITY_VERIFIER=$GOOGLE_IDENTITY_VERIFIER
# anvil #4 — dev fallback signer so no wallet extension is needed.
VITE_DEV_PRIVATE_KEY=0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
EOF

echo "wrote $HARNESS/.env and $DEMO_ENV"
