import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { expect, it } from 'vitest'

// Test titles cite the requirements they cover (docs/test-plan.md); traceability maps each row to
// its tests. This keeps the two honest: tested rows are cited, and citations name real rows.

const root = fileURLToPath(new URL('../../', import.meta.url))
const read = (path: string) => readFileSync(join(root, path), 'utf8')

/** Test sources, and the fixtures and tables whose strings become test titles, by path. */
function sources(dir: string): [string, string][] {
  return readdirSync(join(root, dir), { recursive: true, encoding: 'utf8' })
    .filter((path) => /\.(ts|mjs)$/.test(path) && !path.endsWith('.d.ts'))
    .map((path) => [join(dir, path), read(join(dir, path))])
}

// The dev app's browser tests are cited as evidence too.
const files = ['src', 'e2e', 'build', '../../apps/dev/src'].flatMap(sources)

const tagPattern = /\[((?:LIBID|TEST|REQ|KIT|CSP|POPUP)-[^\]\n]*)\]/g
const tagsIn = (text: string) => [...text.matchAll(tagPattern)].map(([, tag]) => tag)
const tags = files.flatMap(([, text]) => tagsIn(text))

/** A tag's IDs, with `A-B-1/2` expanded to `A-B-1` and `A-B-2`. */
function ids(tag: string): string[] {
  const [first, ...rest] = tag.split('/')
  const prefix = first.slice(0, first.lastIndexOf('-') + 1)
  return [first, ...rest.map((suffix) => prefix + suffix)]
}
const cited = new Set(tags.flatMap(ids))

const planned = new Set(
  [...read('docs/test-plan.md').matchAll(/^\| (LIBID-[A-Z]+-\d+[A-Z]?) \|/gm)].map(([, id]) => id),
)

const tested = [
  ...read('docs/traceability.md').matchAll(
    /^\| ((?:LIBID-[A-Z]+|KIT|CSP)-\d+[A-Z]?) \| (Automated|Partial) \|/gm,
  ),
].map(([, id]) => id)

/** Each cited ID and the sources citing it, as the Markdown page docs/citations.md holds. */
function citationPage(): string {
  const byId = new Map<string, Set<string>>()
  for (const [path, text] of files)
    for (const id of tagsIn(text).flatMap(ids)) byId.set(id, (byId.get(id) ?? new Set()).add(path))
  const { compare } = new Intl.Collator('en', { numeric: true })
  const rows = [...byId]
    .sort(([a], [b]) => compare(a, b))
    .map(([id, paths]) => {
      const links = [...paths]
        .sort(compare)
        .map((path) => `[${path.replace(/^(\.\.\/)+/, '')}](../${path})`)
      return `| ${id} | ${links.join(', ')} |`
    })
  return [
    '# Test citations',
    '',
    'Generated by the [traceability check](../src/testing/traceability.test.ts) from the',
    'requirement tags in test titles and in the tables whose strings become titles; refresh it',
    'with `pnpm exec vitest run src/testing/traceability.test.ts -u`.',
    "[Traceability](traceability.md) keeps each requirement's coverage and what remains outstanding.",
    '',
    '| ID | Cited by |',
    '|---|---|',
    ...rows,
    '',
  ].join('\n')
}

it('cites every automated or partially automated requirement in some test', () => {
  expect(tested.length).toBeGreaterThan(0)
  expect(tested.filter((id) => !cited.has(id))).toEqual([])
})

it('cites only requirements the test plan defines', () => {
  const unknown = [...cited].filter((id) => id.startsWith('LIBID-') && !planned.has(id))
  expect(unknown).toEqual([])
})

it('writes each tag as one ID or one slash-joined series, never a list', () => {
  const malformed = tags.filter(
    (tag) => !/^[A-Z]+(?:-[A-Z]+)?-\d+[A-Z]?(?:\/\d+[A-Z]?)*$/.test(tag),
  )
  expect(malformed).toEqual([])
})

it('keeps the generated citation map current', async () => {
  await expect(citationPage()).toMatchFileSnapshot('../../docs/citations.md')
})
